networks:
  test: null
services:
  ca_orderer:
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    container_name: ca_orderer
    environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_CA_NAME=ca-orderer
    - FABRIC_CA_SERVER_TLS_ENABLED=true
    - FABRIC_CA_SERVER_PORT=8054
    image: hyperledger/fabric-ca:$IMAGE_TAG
    networks:
    - test
    ports:
    - 8054:8054
    volumes:
    - ../organizations/fabric-ca/ordererOrg:/etc/hyperledger/fabric-ca-server
  ca_tg1:
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    container_name: ca_tg1
    environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_CA_NAME=ca-tg1
    - FABRIC_CA_SERVER_TLS_ENABLED=true
    - FABRIC_CA_SERVER_PORT=7054
    image: hyperledger/fabric-ca:$IMAGE_TAG
    networks:
    - test
    ports:
    - 7054:7054
    volumes:
    - ../organizations/fabric-ca/tg1:/etc/hyperledger/fabric-ca-server
version: '2'
