networks:
  test: null
services:
  couchdb0:
    container_name: couchdb0
    environment:
    - COUCHDB_USER=admin
    - COUCHDB_PASSWORD=adminpw
    image: couchdb:3.1
    networks:
    - test
    ports:
    - 5984:5984
  peer0.tg1.hn.com:
    depends_on:
    - couchdb0
    environment:
    - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
    - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
    - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
version: '2'
