networks:
  test: null
services:
  ca_car1:
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    container_name: ca_car1
    environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_CA_NAME=ca-car1
    - FABRIC_CA_SERVER_TLS_ENABLED=true
    - FABRIC_CA_SERVER_PORT=7054
    image: hyperledger/fabric-ca
    networks:
    - test
    ports:
    - 7054:7054
    volumes:
    - ../organizations/fabric-ca/car1:/etc/hyperledger/fabric-ca-server
  ca_car2:
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    container_name: ca_car2
    environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_CA_NAME=ca-car2
    - FABRIC_CA_SERVER_TLS_ENABLED=true
    - FABRIC_CA_SERVER_PORT=8054
    image: hyperledger/fabric-ca
    networks:
    - test
    ports:
    - 8054:8054
    volumes:
    - ../organizations/fabric-ca/car2:/etc/hyperledger/fabric-ca-server
  ca_car3:
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    container_name: ca_car3
    environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_CA_NAME=ca-car3
    - FABRIC_CA_SERVER_TLS_ENABLED=true
    - FABRIC_CA_SERVER_PORT=9054
    image: hyperledger/fabric-ca
    networks:
    - test
    ports:
    - 9054:9054
    volumes:
    - ../organizations/fabric-ca/car3:/etc/hyperledger/fabric-ca-server
  ca_car4:
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    container_name: ca_car4
    environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_CA_NAME=ca-car4
    - FABRIC_CA_SERVER_TLS_ENABLED=true
    - FABRIC_CA_SERVER_PORT=10054
    image: hyperledger/fabric-ca
    networks:
    - test
    ports:
    - 10054:10054
    volumes:
    - ../organizations/fabric-ca/car4:/etc/hyperledger/fabric-ca-server
  ca_car5:
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    container_name: ca_car5
    environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_CA_NAME=ca-car5
    - FABRIC_CA_SERVER_TLS_ENABLED=true
    - FABRIC_CA_SERVER_PORT=11054
    image: hyperledger/fabric-ca
    networks:
    - test
    ports:
    - 11054:11054
    volumes:
    - ../organizations/fabric-ca/car5:/etc/hyperledger/fabric-ca-server
  ca_main:
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    container_name: ca_main
    environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_CA_NAME=ca-main
    - FABRIC_CA_SERVER_TLS_ENABLED=true
    - FABRIC_CA_SERVER_PORT=12054
    image: hyperledger/fabric-ca
    networks:
    - test
    ports:
    - 12054:12054
    volumes:
    - ../organizations/fabric-ca/main:/etc/hyperledger/fabric-ca-server
  ca_orderer:
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    container_name: ca_orderer
    environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_CA_NAME=ca-orderer
    - FABRIC_CA_SERVER_TLS_ENABLED=true
    - FABRIC_CA_SERVER_PORT=13054
    image: hyperledger/fabric-ca
    networks:
    - test
    ports:
    - 13054:13054
    volumes:
    - ../organizations/fabric-ca/ordererOrg:/etc/hyperledger/fabric-ca-server
version: '2'
