networks:
  test: null
services:
  orderer.hn.com:
    command: orderer
    container_name: orderer.hn.com
    environment:
    - FABRIC_LOGGING_SPEC=INFO
    - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
    - ORDERER_GENERAL_LISTENPORT=7050
    - ORDERER_GENERAL_GENESISMETHOD=file
    - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
    - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
    - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
    - ORDERER_GENERAL_TLS_ENABLED=true
    - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
    - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
    - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
    - ORDERER_KAFKA_VERBOSE=true
    - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
    - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
    - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    image: hyperledger/fabric-orderer
    networks:
    - test
    ports:
    - 7050:7050
    volumes:
    - ../system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../organizations/ordererOrganizations/hn.com/orderers/orderer.hn.com/msp:/var/hyperledger/orderer/msp
    - ../organizations/ordererOrganizations/hn.com/orderers/orderer.hn.com/tls/:/var/hyperledger/orderer/tls
    - orderer.hn.com:/var/hyperledger/production/orderer
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
  peer0.car1.hn.com:
    command: peer node start
    container_name: peer0.car1.hn.com
    depends_on:
    - orderer.hn.com
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=docker_test
    - FABRIC_LOGGING_SPEC=INFO
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - CORE_PEER_ID=peer0.car1.hn.com
    - CORE_PEER_ADDRESS=peer0.car1.hn.com:7051
    - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
    - CORE_PEER_CHAINCODEADDRESS=peer0.car1.hn.com:7052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.car1.hn.com:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.car1.hn.com:7051
    - CORE_PEER_LOCALMSPID=Car1MSP
    image: hyperledger/fabric-peer
    networks:
    - test
    ports:
    - 7051:7051
    volumes:
    - /var/run/:/host/var/run/
    - ../organizations/peerOrganizations/car1.hn.com/peers/peer0.car1.hn.com/msp:/etc/hyperledger/fabric/msp
    - ../organizations/peerOrganizations/car1.hn.com/peers/peer0.car1.hn.com/tls:/etc/hyperledger/fabric/tls
    - peer0.car1.hn.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
  peer0.car2.hn.com:
    command: peer node start
    container_name: peer0.car2.hn.com
    depends_on:
    - orderer.hn.com
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=docker_test
    - FABRIC_LOGGING_SPEC=INFO
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - CORE_PEER_ID=peer0.car2.hn.com
    - CORE_PEER_ADDRESS=peer0.car2.hn.com:8051
    - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
    - CORE_PEER_CHAINCODEADDRESS=peer0.car2.hn.com:8052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.car2.hn.com:8051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.car2.hn.com:8051
    - CORE_PEER_LOCALMSPID=Car2MSP
    image: hyperledger/fabric-peer
    networks:
    - test
    ports:
    - 8051:8051
    volumes:
    - /var/run/:/host/var/run/
    - ../organizations/peerOrganizations/car2.hn.com/peers/peer0.car2.hn.com/msp:/etc/hyperledger/fabric/msp
    - ../organizations/peerOrganizations/car2.hn.com/peers/peer0.car2.hn.com/tls:/etc/hyperledger/fabric/tls
    - peer0.car2.hn.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
  peer0.car3.hn.com:
    command: peer node start
    container_name: peer0.car3.hn.com
    depends_on:
    - orderer.hn.com
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=docker_test
    - FABRIC_LOGGING_SPEC=INFO
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - CORE_PEER_ID=peer0.car3.hn.com
    - CORE_PEER_ADDRESS=peer0.car3.hn.com:9051
    - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
    - CORE_PEER_CHAINCODEADDRESS=peer0.car3.hn.com:9052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.car3.hn.com:9051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.car3.hn.com:9051
    - CORE_PEER_LOCALMSPID=Car3MSP
    image: hyperledger/fabric-peer
    networks:
    - test
    ports:
    - 9051:9051
    volumes:
    - /var/run/:/host/var/run/
    - ../organizations/peerOrganizations/car3.hn.com/peers/peer0.car3.hn.com/msp:/etc/hyperledger/fabric/msp
    - ../organizations/peerOrganizations/car3.hn.com/peers/peer0.car3.hn.com/tls:/etc/hyperledger/fabric/tls
    - peer0.car3.hn.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
  peer0.car4.hn.com:
    command: peer node start
    container_name: peer0.car4.hn.com
    depends_on:
    - orderer.hn.com
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=docker_test
    - FABRIC_LOGGING_SPEC=INFO
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - CORE_PEER_ID=peer0.car4.hn.com
    - CORE_PEER_ADDRESS=peer0.car4.hn.com:10051
    - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
    - CORE_PEER_CHAINCODEADDRESS=peer0.car4.hn.com:10052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.car4.hn.com:10051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.car4.hn.com:10051
    - CORE_PEER_LOCALMSPID=Car4MSP
    image: hyperledger/fabric-peer
    networks:
    - test
    ports:
    - 10051:10051
    volumes:
    - /var/run/:/host/var/run/
    - ../organizations/peerOrganizations/car4.hn.com/peers/peer0.car4.hn.com/msp:/etc/hyperledger/fabric/msp
    - ../organizations/peerOrganizations/car4.hn.com/peers/peer0.car4.hn.com/tls:/etc/hyperledger/fabric/tls
    - peer0.car4.hn.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
  peer0.car5.hn.com:
    command: peer node start
    container_name: peer0.car5.hn.com
    depends_on:
    - orderer.hn.com
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=docker_test
    - FABRIC_LOGGING_SPEC=INFO
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - CORE_PEER_ID=peer0.car5.hn.com
    - CORE_PEER_ADDRESS=peer0.car5.hn.com:11051
    - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
    - CORE_PEER_CHAINCODEADDRESS=peer0.car5.hn.com:11052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.car5.hn.com:11051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.car5.hn.com:11051
    - CORE_PEER_LOCALMSPID=Car5MSP
    image: hyperledger/fabric-peer
    networks:
    - test
    ports:
    - 11051:11051
    volumes:
    - /var/run/:/host/var/run/
    - ../organizations/peerOrganizations/car5.hn.com/peers/peer0.car5.hn.com/msp:/etc/hyperledger/fabric/msp
    - ../organizations/peerOrganizations/car5.hn.com/peers/peer0.car5.hn.com/tls:/etc/hyperledger/fabric/tls
    - peer0.car5.hn.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
  peer0.main.hn.com:
    command: peer node start
    container_name: peer0.main.hn.com
    depends_on:
    - orderer.hn.com
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=docker_test
    - FABRIC_LOGGING_SPEC=INFO
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - CORE_PEER_ID=peer0.main.hn.com
    - CORE_PEER_ADDRESS=peer0.main.hn.com:12051
    - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
    - CORE_PEER_CHAINCODEADDRESS=peer0.main.hn.com:12052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.main.hn.com:12051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.main.hn.com:12051
    - CORE_PEER_LOCALMSPID=MainMSP
    image: hyperledger/fabric-peer
    networks:
    - test
    ports:
    - 12051:12051
    volumes:
    - /var/run/:/host/var/run/
    - ../organizations/peerOrganizations/main.hn.com/peers/peer0.main.hn.com/msp:/etc/hyperledger/fabric/msp
    - ../organizations/peerOrganizations/main.hn.com/peers/peer0.main.hn.com/tls:/etc/hyperledger/fabric/tls
    - peer0.main.hn.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
version: '2'
volumes:
  orderer.hn.com: null
  peer0.car1.hn.com: null
  peer0.car2.hn.com: null
  peer0.car3.hn.com: null
  peer0.car4.hn.com: null
  peer0.car5.hn.com: null
  peer0.main.hn.com: null
