networks:
  test: null
services:
  couchdb0:
    container_name: couchdb0
    environment:
    - COUCHDB_USER=admin
    - COUCHDB_PASSWORD=adminpw
    image: couchdb:3.1
    networks:
    - test
    ports:
    - 5984:5984
  couchdb1:
    container_name: couchdb1
    environment:
    - COUCHDB_USER=admin
    - COUCHDB_PASSWORD=adminpw
    image: couchdb:3.1
    networks:
    - test
    ports:
    - 6984:5984
  couchdb2:
    container_name: couchdb2
    environment:
    - COUCHDB_USER=admin
    - COUCHDB_PASSWORD=adminpw
    image: couchdb:3.1
    networks:
    - test
    ports:
    - 7984:5984
  couchdb3:
    container_name: couchdb3
    environment:
    - COUCHDB_USER=admin
    - COUCHDB_PASSWORD=adminpw
    image: couchdb:3.1
    networks:
    - test
    ports:
    - 8984:5984
  couchdb4:
    container_name: couchdb4
    environment:
    - COUCHDB_USER=admin
    - COUCHDB_PASSWORD=adminpw
    image: couchdb:3.1
    networks:
    - test
    ports:
    - 9984:5984
  couchdb5:
    container_name: couchdb5
    environment:
    - COUCHDB_USER=admin
    - COUCHDB_PASSWORD=adminpw
    image: couchdb:3.1
    networks:
    - test
    ports:
    - 10984:5984
  peer0.customer.hn.com:
    depends_on:
    - couchdb2
    environment:
    - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
    - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
    - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
  peer0.item.hn.com:
    depends_on:
    - couchdb5
    environment:
    - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb5:5984
    - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
    - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
  peer0.seller1.hn.com:
    depends_on:
    - couchdb0
    environment:
    - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
    - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
    - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
  peer0.seller2.hn.com:
    depends_on:
    - couchdb1
    environment:
    - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
    - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
    - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
  peer1.customer.hn.com:
    depends_on:
    - couchdb3
    environment:
    - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb3:5984
    - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
    - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
  peer2.customer.hn.com:
    depends_on:
    - couchdb4
    environment:
    - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb4:5984
    - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
    - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
version: '2'
