networks:
  test: null
services:
  orderer.hn.com:
    command: orderer
    container_name: orderer.hn.com
    environment:
    - FABRIC_LOGGING_SPEC=INFO
    - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
    - ORDERER_GENERAL_LISTENPORT=7050
    - ORDERER_GENERAL_GENESISMETHOD=file
    - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
    - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
    - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
    - ORDERER_GENERAL_TLS_ENABLED=true
    - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
    - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
    - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
    - ORDERER_KAFKA_VERBOSE=true
    - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
    - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
    - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    image: hyperledger/fabric-orderer
    networks:
    - test
    ports:
    - 7050:7050
    volumes:
    - ../system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../organizations/ordererOrganizations/hn.com/orderers/orderer.hn.com/msp:/var/hyperledger/orderer/msp
    - ../organizations/ordererOrganizations/hn.com/orderers/orderer.hn.com/tls/:/var/hyperledger/orderer/tls
    - orderer.hn.com:/var/hyperledger/production/orderer
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
  peer0.customer.hn.com:
    command: peer node start
    container_name: peer0.customer.hn.com
    depends_on:
    - orderer.hn.com
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=docker_test
    - FABRIC_LOGGING_SPEC=INFO
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - CORE_PEER_ID=peer0.customer.hn.com
    - CORE_PEER_ADDRESS=peer0.customer.hn.com:9051
    - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
    - CORE_PEER_CHAINCODEADDRESS=peer0.customer.hn.com:9052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.customer.hn.com:9051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.customer.hn.com:9051
    - CORE_PEER_LOCALMSPID=CustomerMSP
    image: hyperledger/fabric-peer
    networks:
    - test
    ports:
    - 9051:9051
    volumes:
    - /var/run/:/host/var/run/
    - ../organizations/peerOrganizations/customer.hn.com/peers/peer0.customer.hn.com/msp:/etc/hyperledger/fabric/msp
    - ../organizations/peerOrganizations/customer.hn.com/peers/peer0.customer.hn.com/tls:/etc/hyperledger/fabric/tls
    - peer0.customer.hn.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
  peer0.item.hn.com:
    command: peer node start
    container_name: peer0.item.hn.com
    depends_on:
    - orderer.hn.com
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=docker_test
    - FABRIC_LOGGING_SPEC=INFO
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - CORE_PEER_ID=peer0.item.hn.com
    - CORE_PEER_ADDRESS=peer0.item.hn.com:12051
    - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
    - CORE_PEER_CHAINCODEADDRESS=peer0.item.hn.com:12052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.item.hn.com:12051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.item.hn.com:12051
    - CORE_PEER_LOCALMSPID=ItemMSP
    image: hyperledger/fabric-peer
    networks:
    - test
    ports:
    - 12051:12051
    volumes:
    - /var/run/:/host/var/run/
    - ../organizations/peerOrganizations/item.hn.com/peers/peer0.item.hn.com/msp:/etc/hyperledger/fabric/msp
    - ../organizations/peerOrganizations/item.hn.com/peers/peer0.item.hn.com/tls:/etc/hyperledger/fabric/tls
    - peer0.item.hn.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
  peer0.seller1.hn.com:
    command: peer node start
    container_name: peer0.seller1.hn.com
    depends_on:
    - orderer.hn.com
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=docker_test
    - FABRIC_LOGGING_SPEC=INFO
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - CORE_PEER_ID=peer0.seller1.hn.com
    - CORE_PEER_ADDRESS=peer0.seller1.hn.com:7051
    - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
    - CORE_PEER_CHAINCODEADDRESS=peer0.seller1.hn.com:7052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.seller1.hn.com:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.seller1.hn.com:7051
    - CORE_PEER_LOCALMSPID=Seller1MSP
    image: hyperledger/fabric-peer
    networks:
    - test
    ports:
    - 7051:7051
    volumes:
    - /var/run/:/host/var/run/
    - ../organizations/peerOrganizations/seller1.hn.com/peers/peer0.seller1.hn.com/msp:/etc/hyperledger/fabric/msp
    - ../organizations/peerOrganizations/seller1.hn.com/peers/peer0.seller1.hn.com/tls:/etc/hyperledger/fabric/tls
    - peer0.seller1.hn.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
  peer0.seller2.hn.com:
    command: peer node start
    container_name: peer0.seller2.hn.com
    depends_on:
    - orderer.hn.com
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=docker_test
    - FABRIC_LOGGING_SPEC=INFO
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - CORE_PEER_ID=peer0.seller2.hn.com
    - CORE_PEER_ADDRESS=peer0.seller2.hn.com:8051
    - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
    - CORE_PEER_CHAINCODEADDRESS=peer0.seller2.hn.com:8052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.seller2.hn.com:8051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.seller2.hn.com:8051
    - CORE_PEER_LOCALMSPID=Seller2MSP
    image: hyperledger/fabric-peer
    networks:
    - test
    ports:
    - 8051:8051
    volumes:
    - /var/run/:/host/var/run/
    - ../organizations/peerOrganizations/seller2.hn.com/peers/peer0.seller2.hn.com/msp:/etc/hyperledger/fabric/msp
    - ../organizations/peerOrganizations/seller2.hn.com/peers/peer0.seller2.hn.com/tls:/etc/hyperledger/fabric/tls
    - peer0.seller2.hn.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
  peer1.customer.hn.com:
    command: peer node start
    container_name: peer1.customer.hn.com
    depends_on:
    - orderer.hn.com
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=docker_test
    - FABRIC_LOGGING_SPEC=INFO
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - CORE_PEER_ID=peer1.customer.hn.com
    - CORE_PEER_ADDRESS=peer1.customer.hn.com:10051
    - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
    - CORE_PEER_CHAINCODEADDRESS=peer1.customer.hn.com:10052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.customer.hn.com:10051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.customer.hn.com:10051
    - CORE_PEER_LOCALMSPID=CustomerMSP
    image: hyperledger/fabric-peer
    networks:
    - test
    ports:
    - 10051:10051
    volumes:
    - /var/run/:/host/var/run/
    - ../organizations/peerOrganizations/customer.hn.com/peers/peer1.customer.hn.com/msp:/etc/hyperledger/fabric/msp
    - ../organizations/peerOrganizations/customer.hn.com/peers/peer1.customer.hn.com/tls:/etc/hyperledger/fabric/tls
    - peer1.customer.hn.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
  peer2.customer.hn.com:
    command: peer node start
    container_name: peer2.customer.hn.com
    depends_on:
    - orderer.hn.com
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=docker_test
    - FABRIC_LOGGING_SPEC=INFO
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - CORE_PEER_ID=peer2.customer.hn.com
    - CORE_PEER_ADDRESS=peer2.customer.hn.com:11051
    - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
    - CORE_PEER_CHAINCODEADDRESS=peer2.customer.hn.com:11052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.customer.hn.com:11051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.customer.hn.com:11051
    - CORE_PEER_LOCALMSPID=CustomerMSP
    image: hyperledger/fabric-peer
    networks:
    - test
    ports:
    - 11051:11051
    volumes:
    - /var/run/:/host/var/run/
    - ../organizations/peerOrganizations/customer.hn.com/peers/peer2.customer.hn.com/msp:/etc/hyperledger/fabric/msp
    - ../organizations/peerOrganizations/customer.hn.com/peers/peer2.customer.hn.com/tls:/etc/hyperledger/fabric/tls
    - peer2.customer.hn.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
version: '2'
volumes:
  orderer.hn.com: null
  peer0.customer.hn.com: null
  peer0.item.hn.com: null
  peer0.seller1.hn.com: null
  peer0.seller2.hn.com: null
  peer1.customer.hn.com: null
  peer2.customer.hn.com: null
