version: "2"

volumes:
  orderer1.hn.com:
  orderer2.hn.com:
  peer0.ins1.hn.com:
  peer0.ins2.hn.com:
  peer0.ins3.hn.com:
  peer0.ga1.hn.com:
  peer0.ga2.hn.com:

networks:
  test:


services:

  orderer1.hn.com:
    container_name: orderer1.hn.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer1.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ../system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer1.genesis.block
      - ../organizations/ordererOrganizations/hn.com/orderers/orderer1.hn.com/msp:/var/hyperledger/orderer/msp
      - ../organizations/ordererOrganizations/hn.com/orderers/orderer1.hn.com/tls/:/var/hyperledger/orderer/tls
      - orderer1.hn.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
    networks:
      - test

  orderer2.hn.com:
    container_name: orderer2.hn.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=8050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer2.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ../system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer2.genesis.block
      - ../organizations/ordererOrganizations/hn.com/orderers/orderer2.hn.com/msp:/var/hyperledger/orderer/msp
      - ../organizations/ordererOrganizations/hn.com/orderers/orderer2.hn.com/tls/:/var/hyperledger/orderer/tls
      - orderer2.hn.com:/var/hyperledger/production/orderer
    ports:
      - 8050:8050
    networks:
      - test

  peer0.ins1.hn.com:
    container_name: peer0.ins1.hn.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=docker_test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.ins1.hn.com
      - CORE_PEER_ADDRESS=peer0.ins1.hn.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.ins1.hn.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.ins1.hn.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.ins1.hn.com:7051
      - CORE_PEER_LOCALMSPID=Ins1MSP
    volumes:
      - /var/run/:/host/var/run/
      - ../organizations/peerOrganizations/ins1.hn.com/peers/peer0.ins1.hn.com/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/ins1.hn.com/peers/peer0.ins1.hn.com/tls:/etc/hyperledger/fabric/tls
      - peer0.ins1.hn.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    depends_on:
      - orderer1.hn.com
      - orderer2.hn.com
    ports:
      - 7051:7051
    networks:
      - test

  peer0.ins2.hn.com:
    container_name: peer0.ins2.hn.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=docker_test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.ins2.hn.com
      - CORE_PEER_ADDRESS=peer0.ins2.hn.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer0.ins2.hn.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.ins2.hn.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.ins2.hn.com:8051
      - CORE_PEER_LOCALMSPID=Ins2MSP
    volumes:
      - /var/run/:/host/var/run/
      - ../organizations/peerOrganizations/ins2.hn.com/peers/peer0.ins2.hn.com/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/ins2.hn.com/peers/peer0.ins2.hn.com/tls:/etc/hyperledger/fabric/tls
      - peer0.ins2.hn.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    depends_on:
      - orderer1.hn.com
      - orderer2.hn.com
    ports:
      - 8051:8051
    networks:
      - test

  peer0.ins3.hn.com:
    container_name: peer0.ins3.hn.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=docker_test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.ins3.hn.com
      - CORE_PEER_ADDRESS=peer0.ins3.hn.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.ins3.hn.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.ins3.hn.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.ins3.hn.com:9051
      - CORE_PEER_LOCALMSPID=Ins3MSP
    volumes:
      - /var/run/:/host/var/run/
      - ../organizations/peerOrganizations/ins3.hn.com/peers/peer0.ins3.hn.com/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/ins3.hn.com/peers/peer0.ins3.hn.com/tls:/etc/hyperledger/fabric/tls
      - peer0.ins3.hn.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    depends_on:
      - orderer1.hn.com
      - orderer2.hn.com
    ports:
      - 9051:9051
    networks:
      - test

  peer0.ga1.hn.com:
    container_name: peer0.ga1.hn.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=docker_test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.ga1.hn.com
      - CORE_PEER_ADDRESS=peer0.ga1.hn.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer0.ga1.hn.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.ga1.hn.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.ga1.hn.com:10051
      - CORE_PEER_LOCALMSPID=Ga1MSP
    volumes:
      - /var/run/:/host/var/run/
      - ../organizations/peerOrganizations/ga1.hn.com/peers/peer0.ga1.hn.com/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/ga1.hn.com/peers/peer0.ga1.hn.com/tls:/etc/hyperledger/fabric/tls
      - peer0.ga1.hn.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    depends_on:
      - orderer1.hn.com
      - orderer2.hn.com
    ports:
      - 10051:10051
    networks:
      - test

  peer0.ga2.hn.com:
    container_name: peer0.ga2.hn.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=docker_test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.ga2.hn.com
      - CORE_PEER_ADDRESS=peer0.ga2.hn.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.ga2.hn.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.ga2.hn.com:11051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.ga2.hn.com:11051
      - CORE_PEER_LOCALMSPID=Ga2MSP
    volumes:
      - /var/run/:/host/var/run/
      - ../organizations/peerOrganizations/ga2.hn.com/peers/peer0.ga2.hn.com/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/ga2.hn.com/peers/peer0.ga2.hn.com/tls:/etc/hyperledger/fabric/tls
      - peer0.ga2.hn.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    depends_on:
      - orderer1.hn.com
      - orderer2.hn.com
    ports:
      - 11051:11051
    networks:
      - test
