networks:
  test: null
services:
  employee0.employee.hn.com:
    command: peer node start
    container_name: employee0.employee.hn.com
    depends_on:
    - orderer.hn.com
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=docker_test
    - FABRIC_LOGGING_SPEC=INFO
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - CORE_PEER_ID=employee0.employee.hn.com
    - CORE_PEER_ADDRESS=employee0.employee.hn.com:9051
    - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
    - CORE_PEER_CHAINCODEADDRESS=employee0.employee.hn.com:9052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
    - CORE_PEER_GOSSIP_BOOTSTRAP=employee0.employee.hn.com:9051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=employee0.employee.hn.com:9051
    - CORE_PEER_LOCALMSPID=EmployeeMSP
    image: hyperledger/fabric-peer
    networks:
    - test
    ports:
    - 9051:9051
    volumes:
    - /var/run/:/host/var/run/
    - ../organizations/peerOrganizations/employee.hn.com/peers/employee0.employee.hn.com/msp:/etc/hyperledger/fabric/msp
    - ../organizations/peerOrganizations/employee.hn.com/peers/employee0.employee.hn.com/tls:/etc/hyperledger/fabric/tls
    - employee0.employee.hn.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
  employee1.employee.hn.com:
    command: peer node start
    container_name: employee1.employee.hn.com
    depends_on:
    - orderer.hn.com
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=docker_test
    - FABRIC_LOGGING_SPEC=INFO
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - CORE_PEER_ID=employee1.employee.hn.com
    - CORE_PEER_ADDRESS=employee1.employee.hn.com:10051
    - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
    - CORE_PEER_CHAINCODEADDRESS=employee1.employee.hn.com:10052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
    - CORE_PEER_GOSSIP_BOOTSTRAP=employee1.employee.hn.com:10051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=employee1.employee.hn.com:10051
    - CORE_PEER_LOCALMSPID=EmployeeMSP
    image: hyperledger/fabric-peer
    networks:
    - test
    ports:
    - 10051:10051
    volumes:
    - /var/run/:/host/var/run/
    - ../organizations/peerOrganizations/employee.hn.com/peers/employee1.employee.hn.com/msp:/etc/hyperledger/fabric/msp
    - ../organizations/peerOrganizations/employee.hn.com/peers/employee1.employee.hn.com/tls:/etc/hyperledger/fabric/tls
    - employee1.employee.hn.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
  employee2.employee.hn.com:
    command: peer node start
    container_name: employee2.employee.hn.com
    depends_on:
    - orderer.hn.com
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=docker_test
    - FABRIC_LOGGING_SPEC=INFO
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - CORE_PEER_ID=employee2.employee.hn.com
    - CORE_PEER_ADDRESS=employee2.employee.hn.com:11051
    - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
    - CORE_PEER_CHAINCODEADDRESS=employee2.employee.hn.com:11052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
    - CORE_PEER_GOSSIP_BOOTSTRAP=employee2.employee.hn.com:11051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=employee2.employee.hn.com:11051
    - CORE_PEER_LOCALMSPID=EmployeeMSP
    image: hyperledger/fabric-peer
    networks:
    - test
    ports:
    - 11051:11051
    volumes:
    - /var/run/:/host/var/run/
    - ../organizations/peerOrganizations/employee.hn.com/peers/employee2.employee.hn.com/msp:/etc/hyperledger/fabric/msp
    - ../organizations/peerOrganizations/employee.hn.com/peers/employee2.employee.hn.com/tls:/etc/hyperledger/fabric/tls
    - employee2.employee.hn.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
  employee3.employee.hn.com:
    command: peer node start
    container_name: employee3.employee.hn.com
    depends_on:
    - orderer.hn.com
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=docker_test
    - FABRIC_LOGGING_SPEC=INFO
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - CORE_PEER_ID=employee3.employee.hn.com
    - CORE_PEER_ADDRESS=employee3.employee.hn.com:12051
    - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
    - CORE_PEER_CHAINCODEADDRESS=employee3.employee.hn.com:12052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
    - CORE_PEER_GOSSIP_BOOTSTRAP=employee3.employee.hn.com:12051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=employee3.employee.hn.com:12051
    - CORE_PEER_LOCALMSPID=EmployeeMSP
    image: hyperledger/fabric-peer
    networks:
    - test
    ports:
    - 12051:12051
    volumes:
    - /var/run/:/host/var/run/
    - ../organizations/peerOrganizations/employee.hn.com/peers/employee3.employee.hn.com/msp:/etc/hyperledger/fabric/msp
    - ../organizations/peerOrganizations/employee.hn.com/peers/employee3.employee.hn.com/tls:/etc/hyperledger/fabric/tls
    - employee3.employee.hn.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
  orderer.hn.com:
    command: orderer
    container_name: orderer.hn.com
    environment:
    - FABRIC_LOGGING_SPEC=INFO
    - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
    - ORDERER_GENERAL_LISTENPORT=7050
    - ORDERER_GENERAL_GENESISMETHOD=file
    - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
    - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
    - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
    - ORDERER_GENERAL_TLS_ENABLED=true
    - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
    - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
    - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
    - ORDERER_KAFKA_VERBOSE=true
    - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
    - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
    - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    image: hyperledger/fabric-orderer
    networks:
    - test
    ports:
    - 7050:7050
    volumes:
    - ../system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../organizations/ordererOrganizations/hn.com/orderers/orderer.hn.com/msp:/var/hyperledger/orderer/msp
    - ../organizations/ordererOrganizations/hn.com/orderers/orderer.hn.com/tls/:/var/hyperledger/orderer/tls
    - orderer.hn.com:/var/hyperledger/production/orderer
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
  peer0.career.hn.com:
    command: peer node start
    container_name: peer0.career.hn.com
    depends_on:
    - orderer.hn.com
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=docker_test
    - FABRIC_LOGGING_SPEC=INFO
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - CORE_PEER_ID=peer0.career.hn.com
    - CORE_PEER_ADDRESS=peer0.career.hn.com:13051
    - CORE_PEER_LISTENADDRESS=0.0.0.0:13051
    - CORE_PEER_CHAINCODEADDRESS=peer0.career.hn.com:13052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:13052
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.career.hn.com:13051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.career.hn.com:13051
    - CORE_PEER_LOCALMSPID=CareerMSP
    image: hyperledger/fabric-peer
    networks:
    - test
    ports:
    - 13051:13051
    volumes:
    - /var/run/:/host/var/run/
    - ../organizations/peerOrganizations/career.hn.com/peers/peer0.career.hn.com/msp:/etc/hyperledger/fabric/msp
    - ../organizations/peerOrganizations/career.hn.com/peers/peer0.career.hn.com/tls:/etc/hyperledger/fabric/tls
    - peer0.career.hn.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
  peer0.company1.hn.com:
    command: peer node start
    container_name: peer0.company1.hn.com
    depends_on:
    - orderer.hn.com
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=docker_test
    - FABRIC_LOGGING_SPEC=INFO
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - CORE_PEER_ID=peer0.company1.hn.com
    - CORE_PEER_ADDRESS=peer0.company1.hn.com:7051
    - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
    - CORE_PEER_CHAINCODEADDRESS=peer0.company1.hn.com:7052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.company1.hn.com:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.company1.hn.com:7051
    - CORE_PEER_LOCALMSPID=Company1MSP
    image: hyperledger/fabric-peer
    networks:
    - test
    ports:
    - 7051:7051
    volumes:
    - /var/run/:/host/var/run/
    - ../organizations/peerOrganizations/company1.hn.com/peers/peer0.company1.hn.com/msp:/etc/hyperledger/fabric/msp
    - ../organizations/peerOrganizations/company1.hn.com/peers/peer0.company1.hn.com/tls:/etc/hyperledger/fabric/tls
    - peer0.company1.hn.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
  peer0.company2.hn.com:
    command: peer node start
    container_name: peer0.company2.hn.com
    depends_on:
    - orderer.hn.com
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=docker_test
    - FABRIC_LOGGING_SPEC=INFO
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - CORE_PEER_ID=peer0.company2.hn.com
    - CORE_PEER_ADDRESS=peer0.company2.hn.com:8051
    - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
    - CORE_PEER_CHAINCODEADDRESS=peer0.company2.hn.com:8052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.company2.hn.com:8051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.company2.hn.com:8051
    - CORE_PEER_LOCALMSPID=Company2MSP
    image: hyperledger/fabric-peer
    networks:
    - test
    ports:
    - 8051:8051
    volumes:
    - /var/run/:/host/var/run/
    - ../organizations/peerOrganizations/company2.hn.com/peers/peer0.company2.hn.com/msp:/etc/hyperledger/fabric/msp
    - ../organizations/peerOrganizations/company2.hn.com/peers/peer0.company2.hn.com/tls:/etc/hyperledger/fabric/tls
    - peer0.company2.hn.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
version: '2'
volumes:
  employee0.employee.hn.com: null
  employee1.employee.hn.com: null
  employee2.employee.hn.com: null
  employee3.employee.hn.com: null
  orderer.hn.com: null
  peer0.career.hn.com: null
  peer0.company1.hn.com: null
  peer0.company2.hn.com: null
